-- DropForeignKey
ALTER TABLE "Invoice" DROP CONSTRAINT "Invoice_clientId_fkey";

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "clientId" DROP NOT NULL,
ALTER COLUMN "issueDate" DROP NOT NULL,
ALTER COLUMN "issueDate" DROP DEFAULT,
ALTER COLUMN "dueDate" DROP NOT NULL,
ALTER COLUMN "currency" DROP NOT NULL,
ALTER COLUMN "subtotal" DROP NOT NULL,
ALTER COLUMN "subtotal" SET DEFAULT 0,
ALTER COLUMN "taxRate" DROP NOT NULL,
ALTER COLUMN "taxRate" SET DEFAULT 0,
ALTER COLUMN "discountRate" DROP NOT NULL,
ALTER COLUMN "discountRate" SET DEFAULT 0,
ALTER COLUMN "taxAmount" DROP NOT NULL,
ALTER COLUMN "taxAmount" SET DEFAULT 0,
ALTER COLUMN "discountAmount" DROP NOT NULL,
ALTER COLUMN "discountAmount" SET DEFAULT 0,
ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "total" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "LineItem" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "quantity" SET DEFAULT 0,
ALTER COLUMN "rate" DROP NOT NULL,
ALTER COLUMN "rate" SET DEFAULT 0,
ALTER COLUMN "amount" DROP NOT NULL,
ALTER COLUMN "amount" SET DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
