import type {
  AutoSaveApiPayload,
  InvoiceApiPayload,
  InvoiceFormData,
  InvoiceResponse,
} from "@/types/invoice";

const optStr = (val?: string) => val?.trim() || undefined;
const optNum = (val: number) => (isNaN(val) ? undefined : val);

export const formDataToAutoSavePayload = (
  form: InvoiceFormData,
): AutoSaveApiPayload => ({
  invoiceNumber: optStr(form.invoiceNumber),
  status: form.status || undefined,
  clientId: optStr(form.clientId),
  issueDate: form.issueDate
    ? new Date(form.issueDate).toISOString()
    : undefined,
  dueDate: form.dueDate ? new Date(form.dueDate).toISOString() : undefined,
  currency: form.currency || undefined,
  subtotal: optNum(form.subtotal),
  taxRate: optNum(form.taxRate),
  discountRate: optNum(form.discountRate),
  taxAmount: optNum(form.taxAmount),
  discountAmount: optNum(form.discountAmount),
  total: optNum(form.total),
  bankName: optStr(form.bankName),
  accountHolderName: optStr(form.accountHolderName),
  accountNumber: optStr(form.accountNumber),
  notes: optStr(form.notes),
  senderName: optStr(form.senderName),
  senderEmail: optStr(form.senderEmail),
  senderCompany: optStr(form.senderCompany),
  senderAddress: optStr(form.senderAddress),
  senderPhone: optStr(form.senderPhone),
  senderWebsite: optStr(form.senderWebsite),
  snapshotClientName: optStr(form.snapshotClientName),
  snapshotClientEmail: optStr(form.snapshotClientEmail),
  snapshotClientCompany: optStr(form.snapshotClientCompany),
  snapshotClientAddress: optStr(form.snapshotClientAddress),
  snapshotClientPhone: optStr(form.snapshotClientPhone),
  snapshotClientWebsite: optStr(form.snapshotClientWebsite),
  lineItems: form.lineItems.map(({ id, ...rest }) => ({
    description: optStr(rest.description),
    quantity: optNum(rest.quantity),
    rate: optNum(rest.rate),
    amount: optNum(rest.amount),
  })),
});

export const formDataToApiPayload = (
  form: InvoiceFormData,
): InvoiceApiPayload => ({
  invoiceNumber: form.invoiceNumber.trim(),
  status: form.status,
  clientId: form.clientId,
  issueDate: new Date(form.issueDate).toISOString(),
  dueDate: new Date(form.dueDate).toISOString(),
  currency: form.currency,
  subtotal: form.subtotal,
  taxRate: form.taxRate,
  discountRate: form.discountRate,
  taxAmount: form.taxAmount,
  discountAmount: form.discountAmount,
  total: form.total,
  bankName: optStr(form.bankName),
  accountHolderName: optStr(form.accountHolderName),
  accountNumber: optStr(form.accountNumber),
  notes: optStr(form.notes),
  senderName: form.senderName.trim(),
  senderEmail: optStr(form.senderEmail),
  senderCompany: optStr(form.senderCompany),
  senderAddress: optStr(form.senderAddress),
  senderPhone: optStr(form.senderPhone),
  senderWebsite: optStr(form.senderWebsite),
  snapshotClientName: form.snapshotClientName.trim(),
  snapshotClientEmail: optStr(form.snapshotClientEmail),
  snapshotClientCompany: optStr(form.snapshotClientCompany),
  snapshotClientAddress: optStr(form.snapshotClientAddress),
  snapshotClientPhone: optStr(form.snapshotClientPhone),
  snapshotClientWebsite: optStr(form.snapshotClientWebsite),
  lineItems: form.lineItems.map(({ id, ...rest }) => ({
    ...rest,
    description: rest.description.trim(),
  })),
});

export const invoiceResponseToFormData = (
  invoice: InvoiceResponse,
): InvoiceFormData => ({
  invoiceNumber: invoice.invoiceNumber,
  status: invoice.status,
  clientId: invoice.clientId,
  issueDate: new Date(invoice.issueDate).toISOString().split("T")[0],
  dueDate: invoice.dueDate
    ? new Date(invoice.dueDate).toISOString().split("T")[0]
    : "",
  currency: invoice.currency,
  subtotal: Number(invoice.subtotal),
  taxRate: Number(invoice.taxRate),
  taxAmount: Number(invoice.taxAmount),
  discountRate: Number(invoice.discountRate),
  discountAmount: Number(invoice.discountAmount),
  total: Number(invoice.total),
  bankName: invoice.bankName ?? "",
  accountHolderName: invoice.accountHolderName ?? "",
  accountNumber: invoice.accountNumber ?? "",
  notes: invoice.notes ?? "",
  senderName: invoice.senderName,
  senderEmail: invoice.senderEmail ?? "",
  senderCompany: invoice.senderCompany ?? "",
  senderAddress: invoice.senderAddress ?? "",
  senderPhone: invoice.senderPhone ?? "",
  senderWebsite: invoice.senderWebsite ?? "",
  snapshotClientName: invoice.snapshotClientName ?? "",
  snapshotClientEmail: invoice.snapshotClientEmail ?? "",
  snapshotClientCompany: invoice.snapshotClientCompany ?? "",
  snapshotClientAddress: invoice.snapshotClientAddress ?? "",
  snapshotClientPhone: invoice.snapshotClientPhone ?? "",
  snapshotClientWebsite: invoice.snapshotClientWebsite ?? "",
  lineItems: invoice.lineItems.map((item) => ({
    id: item.id,
    description: item.description,
    quantity: item.quantity,
    rate: item.rate,
    amount: item.amount,
  })),
});
